/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.AlunoDAO;
import DAO.RelatorioDAO;
import Model.Aluno;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author William Tanaka
 */
public class TreinoAluno extends javax.swing.JFrame {

    Aluno alu = new Aluno();
    AlunoDAO daoaluno = new AlunoDAO();
    RelatorioDAO rel = new RelatorioDAO();
    String index;
    String frase = "";
    String item = "";
    
    public TreinoAluno() {
        initComponents();
    }
    
    public TreinoAluno(AlunoDAO a, String cpf) {
        initComponents();
        daoaluno = a;
        rel.criaConexao();
        if(daoaluno.pesquisa(cpf)){
            alu.setId_alu(daoaluno.getAluno().getId_alu());  
            lb_nome.setText(daoaluno.getAluno().getNome_alu());           
            daoaluno.consultarTreino(daoaluno.getAluno().getId_alu());
            listALL1.setModel(daoaluno.listarTreino()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_fechar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listALL = new javax.swing.JList<>();
        bt_relatorios = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lb_lista_medidas = new javax.swing.JLabel();
        bt_cadastrar_medida = new javax.swing.JButton();
        lb_nome = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        bt_fechar1 = new javax.swing.JButton();
        bt_excluir1 = new javax.swing.JButton();
        bt_relatorios1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lb_lista_medidas1 = new javax.swing.JLabel();
        bt_cadastrar_medida1 = new javax.swing.JButton();
        lb_nome1 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        listALL1 = new javax.swing.JList<>();

        bt_fechar.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_fechar.setText("Fechar");
        bt_fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fecharActionPerformed(evt);
            }
        });

        bt_excluir.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_excluir.setText("Excluir medida");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        listALL.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        listALL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listALLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listALL);

        bt_relatorios.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_relatorios.setText("Relatório Evolução");
        bt_relatorios.setActionCommand("Nova medida");
        bt_relatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_relatoriosActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 51, 0));
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Medidas do aluno");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 10, 170, 24);

        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Oi2Fit");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 60, 24);

        lb_lista_medidas.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lb_lista_medidas.setForeground(new java.awt.Color(204, 51, 0));
        lb_lista_medidas.setText("Lista de medidas:");

        bt_cadastrar_medida.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_cadastrar_medida.setText("Cadastrar medida");
        bt_cadastrar_medida.setActionCommand("Nova medida");
        bt_cadastrar_medida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrar_medidaActionPerformed(evt);
            }
        });

        lb_nome.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lb_nome.setForeground(new java.awt.Color(102, 51, 0));

        jToggleButton1.setLabel("Email");
        jToggleButton1.setName("email"); // NOI18N
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bt_fechar1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_fechar1.setText("Fechar");
        bt_fechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_fechar1ActionPerformed(evt);
            }
        });

        bt_excluir1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_excluir1.setText("Excluir treino");
        bt_excluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluir1ActionPerformed(evt);
            }
        });

        bt_relatorios1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_relatorios1.setText("Visualizar Relatório");
        bt_relatorios1.setActionCommand("Nova medida");
        bt_relatorios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_relatorios1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 51, 0));
        jPanel2.setForeground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Treino do aluno");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(370, 10, 170, 24);

        jLabel5.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Oi2Fit");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 10, 60, 24);

        lb_lista_medidas1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lb_lista_medidas1.setForeground(new java.awt.Color(204, 51, 0));
        lb_lista_medidas1.setText("Treino:");

        bt_cadastrar_medida1.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        bt_cadastrar_medida1.setText("Cadastrar treino");
        bt_cadastrar_medida1.setActionCommand("Nova medida");
        bt_cadastrar_medida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cadastrar_medida1ActionPerformed(evt);
            }
        });

        lb_nome1.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lb_nome1.setForeground(new java.awt.Color(102, 51, 0));

        jToggleButton2.setText("Enviar relatório");
        jToggleButton2.setName("email"); // NOI18N
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        listALL1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        listALL1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listALL1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(listALL1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3))
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(120, 120, 120)
                                    .addComponent(lb_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lb_lista_medidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bt_relatorios1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_cadastrar_medida1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(bt_excluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(190, 190, 190)
                            .addComponent(bt_fechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_nome1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_lista_medidas1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jToggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_relatorios1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt_cadastrar_medida1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_excluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_fechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 43, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(574, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bt_fecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fecharActionPerformed
        dispose();
    }//GEN-LAST:event_bt_fecharActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        try{
            listALL1.removeAll();
            int i = Integer.parseInt(item);
            daoaluno.deletarTreino(i);
            daoaluno.consultarTreino(daoaluno.getAluno().getId_alu());
            listALL1.setModel(daoaluno.listarTreino());
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void listALLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listALLMouseClicked

    }//GEN-LAST:event_listALLMouseClicked

    private void bt_relatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_relatoriosActionPerformed
        Map parametros = new HashMap();
        parametros.put("idaluno", daoaluno.getAluno().getId_alu());
        rel.relatorioEvolucaoCorporal(true, parametros);
    }//GEN-LAST:event_bt_relatoriosActionPerformed

    private void bt_cadastrar_medidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrar_medidaActionPerformed
        CadastrarTreino JCadastraTreino = new CadastrarTreino(daoaluno, daoaluno.getAluno().getCpf_alu());
        JCadastraTreino.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_cadastrar_medidaActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        Map parametros = new HashMap();
        parametros.put("idaluno", daoaluno.getAluno().getId_alu());
        rel.enviarEmail(parametros);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void bt_fechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_fechar1ActionPerformed
        dispose();
    }//GEN-LAST:event_bt_fechar1ActionPerformed

    private void bt_excluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluir1ActionPerformed
        try{
            listALL.removeAll();
            int i = Integer.parseInt(item);
            daoaluno.deletarTreino(i);
            daoaluno.consultarTreino(daoaluno.getAluno().getId_alu());
            listALL1.setModel(daoaluno.listarTreino());
        }catch(NumberFormatException a){
            JOptionPane.showMessageDialog(null, "Selecione um registro", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bt_excluir1ActionPerformed

    private void bt_cadastrar_medida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cadastrar_medida1ActionPerformed
        CadastrarTreino JCadastraTreino = new CadastrarTreino(daoaluno, daoaluno.getAluno().getCpf_alu());
        JCadastraTreino.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt_cadastrar_medida1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        Map parametros = new HashMap();
        frase = listALL1.getSelectedValue();
        index = frase.substring(frase.indexOf("Id_Treino") + 9, frase.indexOf("  Treino:"));
        parametros.put("IdAluno", daoaluno.getAluno().getId_alu());
        parametros.put("IdTreino", Integer.parseInt(index));
        rel.enviarEmail(parametros);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void bt_relatorios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_relatorios1ActionPerformed
        Map parametros = new HashMap();
        frase = listALL1.getSelectedValue();
        index = frase.substring(frase.indexOf("Id_Treino") + 9, frase.indexOf("  Treino:"));
        parametros.put("IdAluno", daoaluno.getAluno().getId_alu());
        parametros.put("IdTreino", Integer.parseInt(index));
        rel.relatorioTreino(true, parametros);
    }//GEN-LAST:event_bt_relatorios1ActionPerformed

    private void listALL1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listALL1MouseClicked
        frase = listALL1.getSelectedValue();
        item = frase.substring(frase.indexOf("ID") + 2, frase.indexOf("  Id"));

        System.out.println("id selecionado:" + item);
    }//GEN-LAST:event_listALL1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TreinoAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TreinoAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cadastrar_medida;
    private javax.swing.JButton bt_cadastrar_medida1;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_excluir1;
    private javax.swing.JButton bt_fechar;
    private javax.swing.JButton bt_fechar1;
    private javax.swing.JButton bt_relatorios;
    private javax.swing.JButton bt_relatorios1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JLabel lb_lista_medidas;
    private javax.swing.JLabel lb_lista_medidas1;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_nome1;
    private javax.swing.JList<String> listALL;
    private javax.swing.JList<String> listALL1;
    // End of variables declaration//GEN-END:variables
}
